#!/usr/bin/bash

# set up monitor

DP_STATUS=$(</sys/class/drm/card0-DP-2/status )

if [ "connected" == "$DP_STATUS" ]; then
    /usr/bin/xrandr --output DP-2 --right-of eDP-1 --auto 2>/tmp/screen
    /usr/bin/notify-send --urgency=low -t 5000 "External monitor connected"
else
    /usr/bin/xrandr --output DP-2 --off
    /usr/bin/notify-send --urgency=low -t 5000 "External monitor disconnected"
fi

