#!/bin/bash

# update local git repositories and check if update needed

GITPATH=/home/xander/src:/home/xander/aurbuilds

for BDIR in ${GITPATH//:/ }; do
    for SDIR in ${BDIR}/*/; do
	echo -n  "$SDIR: "
	if [ -d ${SDIR}/.git ]; then
	    git -C ${SDIR} remote update
	    gstatus=$(git -C ${SDIR} status -uno --porcelain)
	else
	    echo "not a git repository"
	    continue
	fi

	if [[ $gstatus ]]; then
	    echo -e '\n' $gstatus
	else
	    echo "nothing to be done"
	fi
    done
done
